site_name: Test Docs
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/mathjax.js
  - https://lib.baomitu.com/mathjax/3.2.2/es5/tex-mml-chtml.js
plugins:
  - tags
  - search
    lang:
      - en
      - ja
    separator: '[\s\-\.]+'
